-- Seed: est_rules — reguły deterministyczne v1 (docs/estimation/05, tabela reguł startowych).
-- DRAFT do finalizacji przez Jakuba (doc 05 l.143: pełną listę z dokładnymi progami tworzy Jakub).
-- Wartości warunków = kanoniczne value z questions.sql. min_level tylko PODNOSI (monotoniczność).
-- Aspect codes muszą istnieć w est_aspects (reguła z błędnym kodem: log+pominięcie w silniku).
-- ODŁOŻONE do F1 (krok „Platforma"): reguły recommend_archetype i archetype_warning
--   (wymagają wizardowego wyboru archetypu; w F0 archetype jest bezpośrednim pytaniem).
-- Idempotencja: jawne id + ON CONFLICT(id) DO UPDATE (est_rules nie ma UNIQUE poza PK; bez zmian schematu 02).
--   Reguły dodane w panelu (F2) dostają id > 100 (autoincrement) i nie kolidują z seedem.

INSERT INTO est_rules (id, name, condition_json, actions_json, reason_template, priority) VALUES
  (1, 'Krytycznosc 24/7',
   '{"q":"downtime_tolerance","op":"eq","val":"critical_247"}',
   '[{"type":"min_level","aspect":"high_availability","level":2},{"type":"min_level","aspect":"observability","level":2},{"type":"min_level","aspect":"infrastructure","level":2}]',
   'Deklarowana krytyczność 24/7 wymaga redundancji i monitoringu.', 10),
  (2, 'Formalne SLA',
   '{"all":[{"q":"sla_formal","op":"eq","val":"konkretny"},{"q":"sla_value","op":"gte","val":99.5}]}',
   '[{"type":"min_level","aspect":"load_balancing","level":1},{"type":"min_level","aspect":"high_availability","level":3},{"type":"min_level","aspect":"observability","level":3},{"type":"min_level","aspect":"disaster_recovery","level":2}]',
   'SLA {sla_value}% wymaga redundancji, load balancingu i monitoringu.', 10),
  (3, 'Krytyczność plus skala',
   '{"all":[{"q":"downtime_tolerance","op":"eq","val":"critical_247"},{"q":"users_concurrent","op":"gte","val":500}]}',
   '[{"type":"min_level","aspect":"load_balancing","level":2},{"type":"min_level","aspect":"high_availability","level":3}]',
   'Krytyczność 24/7 przy {users_concurrent} użytkownikach jednoczesnych wymaga skalowania.', 10),
  (4, 'Sklep fundament e-commerce',
   '{"q":"project_goal","op":"eq","val":"sklep"}',
   '[{"type":"min_level","aspect":"emails","level":1},{"type":"min_level","aspect":"analytics","level":1},{"type":"min_level","aspect":"consent","level":1},{"type":"min_level","aspect":"seo","level":1}]',
   'Sklep wymaga maili transakcyjnych, analityki, zgód i podstaw SEO.', 5),
  (5, 'Ruch duży',
   '{"q":"traffic_monthly","op":"in","val":["300k_1m","ponad_1m"]}',
   '[{"type":"min_level","aspect":"caching","level":2},{"type":"min_level","aspect":"cdn","level":1},{"type":"min_level","aspect":"infrastructure","level":2}]',
   'Duży ruch miesięczny wymaga cache, CDN i mocniejszej infrastruktury.', 5),
  (6, 'B2B wiele organizacji',
   '{"q":"users_type","op":"eq","val":"wiele_organizacji"}',
   '[{"type":"min_level","aspect":"permissions","level":3},{"type":"min_level","aspect":"rls","level":2},{"type":"multiplier","code":"multi_tenant"}]',
   'Wiele organizacji wymaga rozbudowanych uprawnień i izolacji danych (multi-tenant).', 5),
  (7, 'Dane wrażliwe',
   '{"q":"sensitive_data","op":"eq","val":true}',
   '[{"type":"min_level","aspect":"security","level":2},{"type":"min_level","aspect":"rls","level":1}]',
   'Przetwarzanie danych wrażliwych podnosi wymagania bezpieczeństwa.', 5),
  (8, 'Logowanie klientów',
   '{"q":"users_type","op":"neq","val":"nikt"}',
   '[{"type":"min_level","aspect":"authentication","level":1},{"type":"min_level","aspect":"permissions","level":1}]',
   'Logowanie użytkowników wymaga uwierzytelniania i podstawowych uprawnień.', 0),
  (9, 'Migracja z istniejącego systemu',
   '{"q":"existing_data","op":"eq","val":"przenosimy"}',
   '[{"type":"min_level","aspect":"data_migration","level":2}]',
   'Przeniesienie danych z istniejącego systemu wymaga migracji.', 0),
  (10, 'Migracja z zachowaniem SEO',
   '{"all":[{"q":"existing_data","op":"eq","val":"przenosimy"},{"q":"seo_migration","op":"eq","val":true}]}',
   '[{"type":"min_level","aspect":"seo","level":3}]',
   'Zachowanie pozycji przy migracji wymaga pełnego SEO (301, link equity).', 0),
  (11, 'Brak próbki danych',
   '{"all":[{"q":"existing_data","op":"eq","val":"przenosimy"},{"q":"data_sample","op":"eq","val":false}]}',
   '[{"type":"multiplier","code":"data_migration_risk"}]',
   'Migracja bez próbki źródła to ryzyko jakości danych.', 0),
  (12, 'Projekt graficzny od zera',
   '{"q":"design_source","op":"eq","val":"od_zera"}',
   '[{"type":"min_level","aspect":"uxui","level":4}]',
   'Brak identyfikacji wizualnej wymaga projektu od zera.', 0),
  (13, 'Identyfikacja istnieje',
   '{"q":"design_source","op":"eq","val":"identyfikacja"}',
   '[{"type":"min_level","aspect":"uxui","level":2}]',
   'Istniejąca identyfikacja wymaga projektu kluczowych widoków.', 0),
  (14, 'Warsztaty stacjonarne',
   '{"q":"workshops","op":"eq","val":"stacjonarne"}',
   '[{"type":"min_level","aspect":"discovery","level":3},{"type":"cost_item","code":"travel","qty_from":"workshops_travel_km"}]',
   'Warsztaty stacjonarne to rozszerzony discovery i koszt dojazdu.', 0),
  (15, 'Warsztaty online',
   '{"q":"workshops","op":"eq","val":"online"}',
   '[{"type":"min_level","aspect":"discovery","level":2}]',
   'Spotkania online wymagają discovery z mapowaniem wymagań.', 0),
  (16, 'Kampanie płatne',
   '{"q":"ads_planned","op":"answered"}',
   '[{"type":"min_level","aspect":"sem","level":1},{"type":"min_level","aspect":"analytics","level":2}]',
   'Kampanie płatne wymagają setupu SEM i dokładniejszej analityki.', 0),
  (17, 'Pomiar maksymalny',
   '{"q":"tracking_scope","op":"eq","val":"maksymalna"}',
   '[{"type":"min_level","aspect":"sst","level":2},{"type":"min_level","aspect":"consent","level":2}]',
   'Maksymalna dokładność pomiaru wymaga server-side trackingu i zaawansowanych zgód.', 0),
  (18, 'Duży katalog baza',
   '{"q":"products_count","op":"gte","val":1000}',
   '[{"type":"min_level","aspect":"database","level":2}]',
   'Katalog {products_count} pozycji wymaga mocniejszej bazy.', 0),
  (19, 'Duży katalog content',
   '{"all":[{"q":"products_count","op":"gte","val":1000},{"q":"content_source","op":"neq","val":"klient"}]}',
   '[{"type":"min_level","aspect":"content","level":3}]',
   'Wprowadzenie dużego katalogu po naszej stronie to rozbudowany content.', 0),
  (20, 'Warianty masowe lub konfiguracja',
   '{"q":"product_variants","op":"in","val":["masowe","konfigurowalne"]}',
   '[{"type":"min_level","aspect":"backend_logic","level":2},{"type":"min_level","aspect":"database","level":2}]',
   'Masowe warianty/konfiguracja podnoszą złożoność logiki i bazy.', 0),
  (21, 'Hurtownie i feedy',
   '{"any":[{"q":"stock_source","op":"contains","val":"feedy"},{"q":"stock_source","op":"contains","val":"dropshipping"}]}',
   '[{"type":"suggest_integration","code":"feed_standard"},{"type":"min_level","aspect":"observability","level":1}]',
   'Feedy hurtowni wymagają integracji importu i monitoringu.', 0),
  (22, 'Promocje planowane',
   '{"all":[{"q":"promos_planned","op":"eq","val":true},{"q":"project_goal","op":"eq","val":"sklep"}]}',
   '[{"type":"suggest_module","code":"omnibus"},{"type":"suggest_module","code":"promo_engine"}]',
   'Promocje w sklepie wymagają Omnibus (prawo) i silnika promocji.', 0),
  (23, 'Sprzedaż B2B lub mieszana',
   '{"q":"sales_model","op":"in","val":["b2b","mieszana"]}',
   '[{"type":"suggest_module","code":"b2b_pricing"},{"type":"min_level","aspect":"rls","level":1},{"type":"min_level","aspect":"permissions","level":2}]',
   'Sprzedaż B2B wymaga cenników grupowych i rozbudowanych uprawnień.', 0),
  (24, 'Zwroty w systemie',
   '{"q":"returns_handling","op":"eq","val":"system"}',
   '[{"type":"suggest_module","code":"rma"}]',
   'Obsługa zwrotów w systemie to moduł RMA.', 0),
  (25, 'Sztywny deadline',
   '{"q":"deadline_hard","op":"eq","val":true}',
   '[{"type":"multiplier","code":"hard_deadline"}]',
   'Sztywny deadline wymusza pracę równoległą.', 0),
  (26, 'Nowy stack',
   '{"q":"team_new_tech","op":"eq","val":true}',
   '[{"type":"multiplier","code":"new_tech"}]',
   'Stack poza rutyną zespołu to narzut nauki.', 0),
  (27, 'Jezyki 3 plus',
   '{"q":"languages","op":"gte","val":3}',
   '[{"type":"min_level","aspect":"frontend","level":3},{"type":"min_level","aspect":"seo","level":3}]',
   'Wielojezycznosc 3+ wymaga i18n i hreflang.', 0),
  (28, 'Wielojęzyczny sklep',
   '{"all":[{"q":"languages","op":"gte","val":2},{"q":"project_goal","op":"eq","val":"sklep"}]}',
   '[{"type":"min_level","aspect":"emails","level":2}]',
   'Sklep wielojęzyczny wymaga maili w wielu językach.', 0),
  (29, 'Aplikacja custom',
   '{"q":"archetype","op":"in","val":["laravel","headless"]}',
   '[{"type":"min_level","aspect":"apis","level":2},{"type":"min_level","aspect":"cicd","level":2},{"type":"min_level","aspect":"qa","level":2},{"type":"min_level","aspect":"observability","level":2}]',
   'Aplikacja custom wymaga własnego API, CI/CD, QA i observability.', 0),
  (30, 'Hypercare pełny',
   '{"q":"training","op":"eq","val":"hypercare"}',
   '[{"type":"min_level","aspect":"golive","level":3}]',
   'Pełny hypercare to rozszerzone go-live.', 0),
  (31, 'Szkolenie standard',
   '{"q":"training","op":"eq","val":"szkolenie"}',
   '[{"type":"min_level","aspect":"golive","level":2}]',
   'Szkolenie i tydzień opieki to standardowe go-live.', 0),
  (32, 'Konfigurator konsekwencje',
   '{"any":[{"q":"modules","op":"contains","val":"configurator_options"},{"q":"modules","op":"contains","val":"configurator_2d"},{"q":"modules","op":"contains","val":"configurator_3d"}]}',
   '[{"type":"min_level","aspect":"backend_logic","level":2},{"type":"min_level","aspect":"qa","level":2}]',
   'Konfigurator produktu podnosi złożoność logiki i testów.', 0),
  (33, 'Konfigurator wizualny',
   '{"any":[{"q":"modules","op":"contains","val":"configurator_2d"},{"q":"modules","op":"contains","val":"configurator_3d"}]}',
   '[{"type":"min_level","aspect":"frontend","level":3},{"type":"min_level","aspect":"storage","level":2},{"type":"min_level","aspect":"cdn","level":1}]',
   'Wizualizacja wariantów wymaga zaawansowanego frontendu i storage.', 0),
  (34, 'Konfigurator 3D',
   '{"q":"modules","op":"contains","val":"configurator_3d"}',
   '[{"type":"min_level","aspect":"frontend","level":3},{"type":"multiplier","code":"new_tech"},{"type":"cost_item","code":"external"}]',
   'Konfigurator 3D to nowa technologia i koszt modeli 3D.', 0)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name, condition_json = excluded.condition_json, actions_json = excluded.actions_json,
  reason_template = excluded.reason_template, priority = excluded.priority, is_active = 1;

-- f1a: reguły kroku „Platforma" (D21, docs/05) — DRAFT progów do korekty Jakuba.
-- recommend_archetype: neutralne odpowiedzi → rekomendacja archetypu (pre-wybór).
-- archetype_warning: druga linia po wyborze archetypu (warunek na `archetype`).
INSERT INTO est_rules (id, name, condition_json, actions_json, reason_template, priority) VALUES
  (35, 'Rekomendacja: WooCommerce (standardowy sklep)',
   '{"all":[{"q":"project_goal","op":"eq","val":"sklep"},{"q":"products_count","op":"lt","val":2000},{"q":"custom_logic","op":"eq","val":false}]}',
   '[{"type":"recommend_archetype","code":"woocommerce","reason":"Standardowy sklep — najniższy koszt wejścia i utrzymania"}]',
   'Standardowy sklep do 2000 produktów bez nietypowej logiki — WooCommerce.', 0),
  (36, 'Rekomendacja: PrestaShop/WooCommerce (średni katalog)',
   '{"all":[{"q":"project_goal","op":"eq","val":"sklep"},{"q":"products_count","op":"gte","val":2000},{"q":"products_count","op":"lt","val":10000},{"q":"frontend_headless","op":"eq","val":false}]}',
   '[{"type":"recommend_archetype","code":"prestashop","reason":"Średni katalog — wybór wg preferencji utrzymania"},{"type":"recommend_archetype","code":"woocommerce","reason":"Alternatywa dla średniego katalogu"}]',
   'Średni katalog 2–10 tys. bez headless — PrestaShop lub WooCommerce.', 0),
  (37, 'Rekomendacja: Sylius (duży sklep PL)',
   '{"all":[{"q":"project_goal","op":"eq","val":"sklep"},{"any":[{"q":"products_count","op":"gte","val":10000},{"q":"product_variants","op":"eq","val":"masowe"}]},{"any":[{"q":"payments","op":"contains","val":"p24"},{"q":"payments","op":"contains","val":"payu"},{"q":"shipping","op":"contains","val":"inpost"}]}]}',
   '[{"type":"recommend_archetype","code":"sylius","reason":"Duża skala + polskie integracje z półki (BitBag)"}]',
   'Duży katalog/warianty masowe + polskie płatności/kurierzy — Sylius.', 0),
  (38, 'Rekomendacja: Medusa (headless custom)',
   '{"all":[{"q":"project_goal","op":"eq","val":"sklep"},{"q":"frontend_headless","op":"eq","val":true},{"q":"custom_logic","op":"eq","val":true}]}',
   '[{"type":"recommend_archetype","code":"medusa","reason":"Headless-first, TypeScript end-to-end"}]',
   'Sklep headless z nietypową logiką — Medusa.', 0),
  (39, 'Rekomendacja: Laravel (aplikacja/B2B)',
   '{"any":[{"q":"project_goal","op":"eq","val":"aplikacja"},{"q":"project_goal","op":"eq","val":"b2b"}]}',
   '[{"type":"recommend_archetype","code":"laravel","reason":"Logika biznesowa jest produktem; commerce od zera lub moduł"}]',
   'Aplikacja/portal B2B — Laravel.', 0),
  (40, 'Rekomendacja: WordPress/Headless (wizytowka)',
   '{"q":"project_goal","op":"eq","val":"wizytowka"}',
   '[{"type":"recommend_archetype","code":"wordpress","reason":"Waga treści, szybkie wdrożenie"},{"type":"recommend_archetype","code":"headless","reason":"Alternatywa: wydajność/animacje (React/Astro)"}]',
   'Wizytówka/landing — WordPress lub headless (React/Astro).', 0),
  (41, 'Ostrzezenie: wyrastanie z WooCommerce',
   '{"all":[{"any":[{"q":"archetype","op":"eq","val":"woocommerce"},{"q":"archetype","op":"eq","val":"woo_headless"}]},{"any":[{"q":"products_count","op":"gte","val":50000},{"q":"users_concurrent","op":"gte","val":500},{"q":"sales_model","op":"eq","val":"b2b"}]}]}',
   '[{"type":"archetype_warning","message":"Wymagania wykraczają poza komfort WooCommerce — rozważ Sylius/Medusa/Laravel; kontynuacja = ryzyko przebudowy"}]',
   'Skala/B2B przekracza komfort WooCommerce.', 0),
  (42, 'Ostrzeżenie: duży sklep PL pasuje do Sylius',
   '{"all":[{"q":"project_goal","op":"eq","val":"sklep"},{"q":"products_count","op":"gte","val":10000},{"q":"archetype","op":"neq","val":"sylius"}]}',
   '[{"type":"archetype_warning","message":"Profil pasuje do Sylius (polskie integracje z półki — BitBag)"}]',
   'Duży sklep PL zwykle pasuje do Sylius.', 0),
  (43, 'Ostrzeżenie: headless commerce → Medusa',
   '{"all":[{"q":"archetype","op":"eq","val":"headless"},{"q":"project_goal","op":"eq","val":"sklep"},{"q":"custom_logic","op":"eq","val":true}]}',
   '[{"type":"archetype_warning","message":"Rozważ Medusa zamiast budowy commerce od zera"}]',
   'Headless sklep z custom logiką — rozważ Medusa.', 0),
  (44, 'Pierwsze wdrożenie Sylius/Medusa',
   '{"any":[{"q":"archetype","op":"eq","val":"sylius"},{"q":"archetype","op":"eq","val":"medusa"}]}',
   '[{"type":"multiplier","code":"new_tech"}]',
   'Pierwsze wdrożenie Sylius/Medusa — narzut nowej technologii.', 0)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name, condition_json = excluded.condition_json, actions_json = excluded.actions_json,
  reason_template = excluded.reason_template, priority = excluded.priority, is_active = 1;

-- f1a-fix (B.4): recommend dla portal treści — wcześniej brak reguły → sekcja rekomendacji pusta.
INSERT INTO est_rules (id, name, condition_json, actions_json, reason_template, priority) VALUES
  (45, 'Rekomendacja: WordPress (portal treści)',
   '{"q":"project_goal","op":"eq","val":"portal_tresci"}',
   '[{"type":"recommend_archetype","code":"wordpress","reason":"Waga treści, edycja przez klienta, najniższy koszt utrzymania"}]',
   'Portal treści — WordPress (edycja treści, niski koszt utrzymania).', 0),
  (46, 'Rekomendacja: Headless-Astro (portal treści, nowoczesność)',
   '{"all":[{"q":"project_goal","op":"eq","val":"portal_tresci"},{"q":"frontend_headless","op":"eq","val":true}]}',
   '[{"type":"recommend_archetype","code":"headless","reason":"Priorytet nowoczesności/szybkości — Astro/React"}]',
   'Portal treści z priorytetem nowoczesności — headless (Astro/React).', 0),

  -- ── retro-fix (DRAFT do korekty Jakuba) — luki wykryte w retrospektywie Niepodzielnych ──
  -- Problem: skala projektu (liczba widokow, jezyki) NIE wplywala na zaden obszar — 15 unikalnych
  -- widokow zostawalo na frontend poziom 1 (10-25 h). Progi ponizej sa DRAFT.
  (47, 'Skala: wiele widoków',
   '{"q":"views_count","op":"gte","val":8}',
   '[{"type":"min_level","aspect":"frontend","level":2},{"type":"min_level","aspect":"uxui","level":2}]',
   'Projekt ma {views_count} unikalnych widoków — front i projekt UI ponad szablon.', 0),
  (48, 'Skala: dużo widoków',
   '{"q":"views_count","op":"gte","val":20}',
   '[{"type":"min_level","aspect":"frontend","level":3}]',
   '{views_count} widoków to rozbudowany frontend (system komponentów, stany, wydajność).', 0),
  (49, 'Wielojezycznosc',
   '{"q":"languages","op":"gte","val":2}',
   '[{"type":"min_level","aspect":"frontend","level":2},{"type":"min_level","aspect":"content","level":2}]',
   '{languages} wersje językowe wymagają i18n we froncie i obsługi treści w każdej wersji.', 0),

  -- Problem: custom_logic bylo uzywane WYLACZNIE w regulach recommend_archetype z warunkiem
  -- project_goal=sklep — poza sklepem odpowiedz „mamy nietypowa logike" byla martwa.
  (50, 'Nietypowa logika biznesowa',
   '{"q":"custom_logic","op":"eq","val":true}',
   '[{"type":"min_level","aspect":"backend_logic","level":2}]',
   'Nietypowa logika biznesowa poza standardem platformy wymaga własnego backendu.', 0),
  (51, 'Nietypowa logika + integracja niestandardowa',
   '{"all":[{"q":"custom_logic","op":"eq","val":true},{"any":[{"q":"other_integrations","op":"contains","val":"erp_custom"},{"q":"other_integrations","op":"contains","val":"booking"}]}]}',
   '[{"type":"min_level","aspect":"apis","level":2}]',
   'Własna logika spięta z zewnętrznym systemem wymaga warstwy własnego API.', 0),

  -- Problem: obszar emails nie byl podnoszony przez zadna regule — potwierdzenia rezerwacji
  -- i platnosci to maile transakcyjne, ktore zawsze trzeba zrobic.
  (52, 'Maile transakcyjne',
   '{"any":[{"q":"other_integrations","op":"contains","val":"booking"},{"q":"payments","op":"answered"}]}',
   '[{"type":"min_level","aspect":"emails","level":1}]',
   'Rezerwacje/płatności wymagają maili transakcyjnych (potwierdzenia, statusy).', 0),

  -- ── retro#2 (DRAFT): rozmiar KATALOGU wazy takze poza sklepem (listing, karty, filtry, model
  -- danych). Wczesniej products_count wplywalo tylko na rekomendacje archetypu. Progi DRAFT.
  (53, 'Katalog: wiele pozycji',
   '{"q":"products_count","op":"gte","val":20}',
   '[{"type":"min_level","aspect":"frontend","level":2},{"type":"min_level","aspect":"database","level":1}]',
   'Katalog {products_count} pozycji wymaga listingu z filtrowaniem i własnego modelu danych.', 0),
  (54, 'Katalog: duzy',
   '{"q":"products_count","op":"gte","val":100}',
   '[{"type":"min_level","aspect":"database","level":2}]',
   '{products_count} pozycji katalogu to model danych z indeksowaniem i wydajnym wyszukiwaniem.', 0),

  -- ── walidacja rynkowa S1-S4 (DRAFT) ──────────────────────────────────────────────────────
  -- S3 (CRM serwisu) wypadl 31% ponizej rynku: cel „aplikacja" nie podnosil ZADNEGO poziomu —
  -- jedyna regula z „aplikacja" rekomendowala archetyp. Ciezar aplikacji dedykowanej niosl
  -- wylacznie custom_logic (backend_logic>=2), czyli tyle samo co sklep z nietypowym rabatem.
  (55, 'Aplikacja dedykowana',
   '{"q":"project_goal","op":"eq","val":"aplikacja"}',
   '[{"type":"min_level","aspect":"backend_logic","level":3},{"type":"min_level","aspect":"apis","level":2},{"type":"min_level","aspect":"qa","level":2}]',
   'Aplikacja z logowaniem: logika jest produktem — własny backend, API i testy są rdzeniem zakresu.', 0),
  (56, 'Role i uprawnienia (aplikacja / B2B)',
   '{"any":[{"q":"project_goal","op":"eq","val":"aplikacja"},{"q":"project_goal","op":"eq","val":"b2b"}]}',
   '[{"type":"min_level","aspect":"permissions","level":2}]',
   'Różne role użytkowników wymagają modelu uprawnień, nie samego logowania.', 0),

  -- S2 (konfigurator): brak spisanej macierzy zaleznosci nie robil NIC. Teraz podnosi discovery
  -- i ostrzega. Kara Confidence jest w silniku (configuratorWithoutMatrix, engine 1.7) — wzorzec
  -- dataMigrationWithoutSample. BEZ nowego mnoznika (D6 nietkniete).
  (57, 'Konfigurator bez macierzy zależności',
   '{"q":"config_matrix","op":"eq","val":false}',
   '[{"type":"min_level","aspect":"discovery","level":3},{"type":"archetype_warning","message":"Brak spisanej macierzy zależności opcji: zaplanuj Discovery + prototyp przed wiążącą wyceną."}]',
   'Konfigurator bez spisanej macierzy zależności: zakres nieokreślony do czasu Discovery/prototypu.', 0),

  -- (audyt dryfu docs→seeds) „CPQ → produkcja" z docs/05 — udokumentowana, nigdy nie zaseedowana.
  (58, 'CPQ → produkcja',
   '{"q":"modules","op":"contains","val":"cpq_engine"}',
   '[{"type":"min_level","aspect":"backend_logic","level":3},{"type":"min_level","aspect":"apis","level":2}]',
   'Silnik CPQ liczy wycenę produkcyjną i oddaje specyfikację do ERP — własna logika i integracja.', 0)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name, condition_json = excluded.condition_json, actions_json = excluded.actions_json,
  reason_template = excluded.reason_template, priority = excluded.priority, is_active = 1;
