export const BREADCRUMBS_PATH_MAP: Record<string, string> = {
  '/web-development': 'Web Development',
  '/web-development/ecommerce': 'E-commerce',
  '/web-development/landing-page': 'Landing Page',
  '/web-development/corporate': 'Strona Firmowa',
  '/web-development/custom-app': 'Aplikacje Dedykowane',
  '/web-development/rzeszow': 'Rzeszów',
  '/marketing': 'Marketing Cyfrowy',
  '/marketing/google-ads': 'Google Ads',
  '/marketing/meta-ads': 'Meta Ads',
  '/marketing/seo': 'SEO & Content',
  '/marketing/analytics': 'Data & Analityka',
  '/design': 'Grafika & Design',
  '/design/branding': 'Brand Identity',
  '/design/ui-ux': 'UI/UX Design',
  '/design/print': 'Materiały Druk',
  '/design/visual-audit': 'Audyt Wizualny',
  '/contact': 'Kontakt',
  '/offers': 'Oferta',
  '/o-nas': 'O nas',
  '/baza-wiedzy': 'Baza Wiedzy',
  '/baza-wiedzy/redis-optymalizacja': 'Redis - Optymalizacja',
  '/baza-wiedzy/cdn-globalna-wydajnosc': 'CDN - Globalna Wydajność',
  '/baza-wiedzy/optymalizacja-obrazow-webp-avif': 'Next-Gen Image Formats',
  '/baza-wiedzy/waf-bezpieczenstwo': 'WAF - Bezpieczeństwo',
  '/baza-wiedzy/edge-computing': 'Edge Computing',
  '/baza-wiedzy/core-web-vitals-2025': 'Core Web Vitals 2025',
  '/baza-wiedzy/google-ads-skalowanie-budzetu': 'Google Ads - Skalowanie',
};
