/* eslint-disable max-lines */
import { Article } from '../../types';

export const LEGACY_ARTICLES: Article[] = [
  {
    id: 'server-side-tracking',
    title: 'Server-Side Tracking: Ratunek dla Twoich danych',
    description:
      'Twoje kampanie tracą skuteczność przez iOS i AdBlocki? Poznaj Server-Side Tracking i dowiedz się, jak odzyskać 30% danych o konwersjach.',
    category: 'analytics',
    categoryLabel: 'Analityka & Dane',
    image: '/assets/images/server-side-tracking.png',
    date: '22 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/server-side-tracking-koniec-cookies',
    tags: ['CAPI', 'GTM', 'Data Engineering'],
    isFeatured: true,
  },
  {
    id: 'ux-audit',
    title: 'Dlaczego Twój sklep nie sprzedaje? Audyt UX.',
    description:
      'Użytkownicy porzucają koszyki? Często problemem nie jest cena, ale design. Zobacz 5 najczęstszych błędów UX w e-commerce.',
    category: 'design',
    categoryLabel: 'Design & UX',
    image: '/assets/images/audyt-ux.png',
    date: '22 Grudnia 2025',
    readTime: '6 min',
    slug: '/baza-wiedzy/audyt-ux-sklepu-internetowego',
    tags: ['UX/UI', 'E-commerce', 'Conversion'],
    isFeatured: true,
  },
  {
    id: 'redis-optymalizacja',
    title: 'Redis: Kompletny przewodnik po wydajności',
    description:
      '100ms opóźnienia to 1% utraty sprzedaży. Dowiedz się, jak wykorzystać Redis do przyspieszenia aplikacji, cachowania zapytań i obsługi dużego ruchu.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/redis.png',
    date: '22 Grudnia 2025',
    readTime: '10 min',
    slug: '/baza-wiedzy/redis-optymalizacja',
    tags: ['Backend', 'Performance', 'Database'],
    isFeatured: true,
  },
  {
    id: 'cdn-globalna-wydajnosc',
    title: 'CDN: Jak być "blisko" klienta, nawet w Australii?',
    description:
      'Brak CDN to strata pieniędzy. Zobacz, jak Cloudflare i AWS CloudFront przyspieszają ładowanie stron i chronią przed atakami DDoS.',
    category: 'tech',
    categoryLabel: 'Infrastruktura',
    image: '/assets/images/CDN.png',
    date: '28 Grudnia 2025',
    readTime: '8 min',
    slug: '/baza-wiedzy/cdn-globalna-wydajnosc',
    tags: ['Cloud', 'Network', 'Security'],
  },
  {
    id: 'optymalizacja-obrazow-webp-avif',
    title: 'Next-Gen Images: WebP i AVIF – Dieta Twojej Strony',
    description:
      'JPG i PNG to przeszłość. Poznaj nowoczesne formaty, które zmniejszą wagę strony o 80% bez utraty jakości. Popraw Core Web Vitals.',
    category: 'design',
    categoryLabel: 'Design & UX',
    image: '/assets/images/frontend.png',
    date: '30 Grudnia 2025',
    readTime: '6 min',
    slug: '/baza-wiedzy/optymalizacja-obrazow-webp-avif',
    tags: ['UX', 'Performance', 'Images'],
  },
  {
    id: 'waf-bezpieczenstwo',
    title: 'WAF: Twój cyfrowy ochroniarz. Dlaczego firewall to za mało?',
    description:
      'Haker musi mieć rację tylko raz. Zobacz, jak Web Application Firewall chroni Twój sklep przed SQL Injection i atakami botów.',
    category: 'tech',
    categoryLabel: 'Cybersecurity',
    image: '/assets/images/WAF.png',
    date: '2 Grudnia 2026',
    readTime: '12 min',
    slug: '/baza-wiedzy/waf-bezpieczenstwo',
    tags: ['Security', 'WAF', 'Protection'],
  },
  {
    id: 'edge-computing',
    title: 'Edge Computing: Kod na krańcu świata. Chmura to za mało?',
    description:
      'Prawa fizyki są nieubłagane. Zobacz, jak przeniesienie obliczeń bliżej użytkownika napędza IoT, 5G i autonomiczne pojazdy.',
    category: 'tech',
    categoryLabel: 'Future Tech',
    image: '/assets/images/edge-computing.png',
    date: '10 Stycznia 2026',
    readTime: '15 min',
    slug: '/baza-wiedzy/edge-computing',
    tags: ['IoT', 'Cloud', 'Edge'],
  },
  {
    id: 'core-web-vitals-2025',
    title: 'Core Web Vitals 2025: Nowy standard Google Lighthouse',
    description:
      'LCP, CLS i INP – poznaj aktualne wskaźniki na rok 2025. Dowiedz się, jak UX wpływa na Twoje pozycjonowanie i konwersję.',
    category: 'analytics',
    categoryLabel: 'Analityka & SEO',
    image: '/assets/images/core-web-vitals.png',
    date: '15 Stycznia 2026',
    readTime: '10 min',
    slug: '/baza-wiedzy/core-web-vitals-2025',
    tags: ['SEO', 'Lighthouse', 'UX'],
  },
  {
    id: 'google-ads-skalowanie-budzetu',
    title: 'Google Ads: Jak skalować budżet i nie przepalić pieniędzy?',
    description:
      'Dolewasz paliwa, ale samochód nie przyspiesza? Poznaj strategię Smart Scaling i dowiedz się, jak zwiększać wydatki bez utraty ROAS.',
    category: 'marketing',
    categoryLabel: 'Marketing Cyfrowy',
    image: '/assets/images/google-ads.png',
    date: '20 Stycznia 2026',
    readTime: '12 min',
    slug: '/baza-wiedzy/google-ads-skalowanie-budzetu',
    tags: ['PPC', 'Google Ads', 'Strategy'],
  },
  {
    id: 'nextjs-zloty-standard',
    title: 'Next.js: Dlaczego to "Złoty Standard" w 2025 roku?',
    description:
      'React czy Next.js? Poznaj różnice i dowiedz się, dlaczego Next.js jest domyślnym wyborem dla nowoczesnych aplikacji. SEO, SSR i wydajność w jednym.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/nextjs.png',
    date: '23 Grudnia 2025',
    readTime: '15 min',
    slug: '/baza-wiedzy/nextjs-zloty-standard-aplikacji-webowych',
    tags: ['NextJS', 'React', 'SEO', 'Vercel'],
    isFeatured: true,
  },
  {
    id: 'headless-wordpress',
    title: 'Headless WordPress: Zachowaj CMS, który kochasz. Zyskaj prędkość.',
    description:
      'Połącz wygodę WordPressa z wydajnością Next.js. Dowiedz się, dlaczego architektura Headless to przyszłość dużych serwisów contentowych i e-commerce.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/headless-wordpress.png',
    date: '24 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/headless-wordpress-wydajnosc-i-bezpieczenstwo',
    tags: ['Headless', 'WordPress', 'NextJS', 'Jamstack'],
    isFeatured: true,
  },
  {
    id: 'tailwind-css-przyszlosc-ui',
    title: 'Tailwind CSS: Koniec z "generycznym" wyglądem. Przyszłość UI.',
    description:
      'Bootstrap czy Tailwind CSS? Poznaj framework, który zrewolucjonizował frontend. Dowiedz się, jak Utility-First przyspiesza wdrażanie unikalnych projektów.',
    category: 'design',
    categoryLabel: 'Design & UX',
    image: '/assets/images/tailwind-css.png',
    date: '25 Grudnia 2025',
    readTime: '10 min',
    slug: '/baza-wiedzy/tailwind-css-utility-first-przyszlosc-projektowania',
    tags: ['TailwindCSS', 'CSS', 'Frontend', 'DesignSystem'],
    isFeatured: true,
  },
  {
    id: 'typescript-polisa-ubezpieczeniowa',
    title: 'TypeScript: Polisa ubezpieczeniowa dla Twojego kodu.',
    description:
      'TypeScript vs JavaScript – co wybrać do projektu IT? Dowiedz się, jak statyczne typowanie redukuje błędy o 15% i ułatwia skalowanie aplikacji biznesowych.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/nodejs.png',
    date: '26 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/typescript-polisa-ubezpieczeniowa-twojego-kodu',
    tags: ['TypeScript', 'JavaScript', 'Quality', 'Security'],
    isFeatured: true,
  },
  {
    id: 'postgresql-krol-baz-danych',
    title: 'PostgreSQL: Król Baz Danych. Dlaczego giganci wybierają Open Source?',
    description:
      'PostgreSQL vs MySQL vs Oracle – którą bazę wybrać w 2025? Dowiedz się, jak zaoszczędzić na licencjach i zyskać wydajność klasy Enterprise.',
    category: 'tech',
    categoryLabel: 'Bazy Danych',
    image: '/assets/images/PostgreSQL.png',
    date: '27 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/postgresql-krol-baz-danych-open-source-dla-biznesu',
    tags: ['PostgreSQL', 'SQL', 'Database', 'OpenSource', 'Fintech'],
    isFeatured: true,
  },
  {
    id: 'mongodb-przyszlosc-big-data',
    title: 'MongoDB: Kiedy tabelki to za mało. Dlaczego NoSQL to przyszłość?',
    description:
      'Poznaj zalety elastycznej struktury dokumentowej (JSON). Dowiedz się, jak skalowanie poziome (Sharding) i kiedy warto porzucić SQL.',
    category: 'tech',
    categoryLabel: 'Bazy Danych',
    image: '/assets/images/mongodb.png',
    date: '28 Grudnia 2025',
    readTime: '11 min',
    slug: '/baza-wiedzy/mongodb-nosql-przyszlosc-big-data-i-dynamicznych-aplikacji',
    tags: ['MongoDB', 'NoSQL', 'BigData', 'Sharding', 'MERN'],
    isFeatured: true,
  },
  {
    id: 'elasticsearch-inteligentna-wyszukiwarka',
    title: 'Elasticsearch: Gdy LIKE %...% to za mało. Wyszukiwarka, która "rozumie".',
    description:
      'Twoja wyszukiwarka nie znajduje produktów z literówkami? Poznaj Elasticsearch. Dowiedz się, czym jest Full-Text Search i jak Fuzzy Matching ratuje sprzedaż.',
    category: 'tech',
    categoryLabel: 'Search & Data',
    image: '/assets/images/elasticsearch.png',
    date: '29 Grudnia 2025',
    readTime: '13 min',
    slug: '/baza-wiedzy/elasticsearch-inteligentna-wyszukiwarka-ecommerce',
    tags: ['Elasticsearch', 'Ecommerce', 'UX', 'Search', 'ELK'],
    isFeatured: true,
  },
  {
    id: 'frontend-kompendium-2025',
    title: 'Frontend bez Tajemnic: Kompletne Kompendium CTO na 2025 rok',
    description:
      'React, Next.js, Vue czy Tailwind? Przewodnik po technologiach frontendowych. Dowiedz się, co wybrać dla e-commerce, a co dla szybkiego MVP.',
    category: 'tech',
    categoryLabel: 'Frontend Architecture',
    image: '/assets/images/frontend.png',
    date: '25 Grudnia 2025',
    readTime: '15 min',
    slug: '/baza-wiedzy/frontend-bez-tajemnic-kompendium-cto',
    tags: ['Frontend', 'React', 'NextJS', 'VueJS', 'TailwindCSS'],
    isFeatured: true,
  },
  {
    id: 'nodejs-jeden-jezyk',
    title: 'Node.js: Jeden język, by rządzić wszystkim. Biznesowy strzał w dziesiątkę',
    description:
      'Czym jest Node.js i dlaczego Netflix oraz Uber zbudowali na nim swoje systemy? Poznaj zalety backendu w JavaScript. Dowiedz się, jak asynchroniczność (Event Loop) zapewnia niesamowitą wydajność.',
    category: 'tech',
    categoryLabel: 'Fullstack Development',
    image: '/assets/images/nodejs.png',
    date: '26 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/nodejs-jeden-jezyk',
    tags: ['NodeJS', 'JavaScript', 'Backend', 'NestJS', 'RealTime'],
    isFeatured: true,
  },
  {
    id: 'go-golang-jezyk-chmury',
    title: 'Go (Golang): Język Chmury. Dlaczego Uber i Twitch przepisali swoje systemy na Go?',
    description:
      'Czym jest Go? Poznaj język stworzony przez Google, który stał się standardem w mikroserwisach. Goroutines, małe zużycie RAM i High-Load.',
    category: 'tech',
    categoryLabel: 'Cloud Engineering',
    image: '/assets/images/go.png',
    date: '27 Grudnia 2025',
    readTime: '11 min',
    slug: '/baza-wiedzy/go-golang-jezyk-chmury',
    tags: ['Go', 'Golang', 'Cloud', 'Microservices', 'Backend'],
    isFeatured: true,
  },
  {
    id: 'laravel-php-framework-szybkie-wdrozenie',
    title: 'Laravel: PHP nie umarło, ono dojrzało. Dlaczego to wciąż Król Szybkiego Wdrożenia?',
    description:
      'Czy warto wybrać Laravel in 2025? Obalamy mity o PHP. Poznaj framework, który oferuje najszybszy Time-to-Market i gotowe moduły (SaaS, płatności).',
    category: 'tech',
    categoryLabel: 'Backend & Rapid Dev',
    image: '/assets/images/laravel.png',
    date: '28 Grudnia 2025',
    readTime: '13 min',
    slug: '/baza-wiedzy/laravel-php-framework-szybkie-wdrozenie',
    tags: ['Laravel', 'PHP', 'SaaS', 'MVP', 'Backend'],
    isFeatured: true,
  },
  {
    id: 'react-js-krol-frontendu',
    title: 'React.js: Król Frontend’u. Dlaczego to najbezpieczniejszy wybór?',
    description:
      'Dlaczego React.js dominuje na rynku IT? Poznaj zalety biblioteki od Meta. Dowiedz się, jak architektura komponentowa i React Native obniżają koszty.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/react-js.png',
    date: '29 Grudnia 2025',
    readTime: '12 min',
    slug: '/baza-wiedzy/react-js-najbezpieczniejsza-technologia-dla-biznesu',
    tags: ['ReactJS', 'Frontend', 'JavaScript', 'ReactNative', 'Meta'],
    isFeatured: true,
  },
  {
    id: 'vue-js-harmonijny-kompromis',
    title: 'Vue.js: Harmonijny kompromis między Reactem a Angularem.',
    description:
      'Poznaj "Progresywny Framework", który łączy łatwość wdrożenia z wydajnością Enterprise. Dowiedz się, dlaczego NASA i GitLab postawiły na Vue.',
    category: 'tech',
    categoryLabel: 'Technologia & Dev',
    image: '/assets/images/vuejs.png',
    date: '30 Grudnia 2025',
    readTime: '10 min',
    slug: '/baza-wiedzy/vue-js-harmonijny-kompromis-react-angular',
    tags: ['VueJS', 'Frontend', 'Nuxt', 'JavaScript', 'MVP'],
    isFeatured: true,
  },
  {
    id: 'python-django-framework-fintech',
    title: 'Python (Django): Framework do zadań specjalnych. Dlaczego Fintechy go kochają?',
    description:
      'Poznaj framework Pythona, który oferuje bezpieczeństwo klasy bankowej i błyskawiczny czas tworzenia MVP. Idealny wybór dla Fintech, SaaS i AI.',
    category: 'tech',
    categoryLabel: 'Backend & Security',
    image: '/assets/images/django.png',
    date: '31 Grudnia 2025',
    readTime: '14 min',
    slug: '/baza-wiedzy/python-django-bezpieczenstwo-fintech-mvp',
    tags: ['Python', 'Django', 'Fintech', 'Security', 'Backend'],
    isFeatured: true,
  },
  {
    id: 'databases-compendium',
    title: 'Bazy Danych bez Tajemnic: PostgreSQL, Redis, MongoDB czy Elasticsearch?',
    description:
      'Jaką bazę danych wybrać? Poznaj koncepcję Polyglot Persistence i dowiedz się, jak łączyć te technologie, by zbudować wydajną aplikację.',
    category: 'tech',
    categoryLabel: 'Architektura Danych',
    image: '/assets/images/database.png',
    date: '23 Grudnia 2025',
    readTime: '15 min',
    slug: '/baza-wiedzy/bazy-danych-kompendium-architekta',
    tags: ['PostgreSQL', 'MongoDB', 'Redis', 'Elasticsearch', 'Architecture'],
    isFeatured: true,
  },
  {
    id: 'backend-compendium',
    title: 'Backend bez Tajemnic: Kompletny Przewodnik CTO na 2025 rok',
    description:
      'Node.js, Python, Go czy Laravel? Poznaj wady i zalety najpopularniejszych technologii backendowych i wybierz architekturę dla swojego biznesu.',
    category: 'tech',
    categoryLabel: 'Backend & Architecture',
    image: '/assets/images/backend.png',
    date: '23 Grudnia 2025',
    readTime: '15 min',
    slug: '/baza-wiedzy/backend-bez-tajemnic-przewodnik-cto',
    tags: ['Backend', 'NodeJS', 'Python', 'Go', 'Laravel', 'Architecture'],
    isFeatured: true,
  },
  {
    id: 'docker-konteneryzacja',
    title: 'Docker: Koniec z wymówką "U mnie działa". Jak kontenery oszczędzają czas?',
    description:
      'Czym jest Docker i konteneryzacja? Dowiedz się, jak usprawnić wdrażanie aplikacji, wyeliminować błędy konfiguracyjne i przyspieszyć pracę zespołu DevOps.',
    category: 'tech',
    categoryLabel: 'DevOps & Cloud',
    image: '/assets/images/docker.png',
    date: '10 Stycznia 2026',
    readTime: '10 min',
    slug: '/baza-wiedzy/docker-konteneryzacja-przewodnik',
    tags: ['Docker', 'DevOps', 'Kubernetes', 'CI/CD', 'Cloud'],
    isFeatured: true,
  },
  {
    id: 'ci-cd-automatyzacja',
    title: 'CI/CD: Dlaczego Twoja aplikacja nie powinna być wdrażana ręcznie?',
    description:
      'Ręczne wgrywanie plików na serwer to rosyjska ruletka. Poznaj Continuous Integration i Deployment – automatyczną autostradę dla Twojego kodu.',
    category: 'tech',
    categoryLabel: 'DevOps & Quality',
    image: '/assets/images/CICD.png',
    date: '12 Stycznia 2026',
    readTime: '11 min',
    slug: '/baza-wiedzy/ci-cd-automatyzacja-wdrozen',
    tags: ['CI/CD', 'DevOps', 'GitHub Actions', 'Automation', 'Quality'],
    isFeatured: true,
  },
  {
    id: 'devops-fundament-biznesu',
    title: 'DevOps: Fundament Nowoczesnego Biznesu. Kompletny przewodnik po infrastrukturze.',
    description:
      'Docker, Kubernetes, AWS i CI/CD – jak te technologie współpracują, by Twój system był skalowalny, bezpieczny i wdrażał się automatycznie.',
    category: 'tech',
    categoryLabel: 'DevOps & Cloud',
    image: '/assets/images/devops.png',
    date: '14 Stycznia 2026',
    readTime: '15 min',
    slug: '/baza-wiedzy/devops-fundament-nowoczesnego-biznesu',
    tags: ['DevOps', 'Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Infrastructure'],
    isFeatured: true,
  },
];
